config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  root "welcome#index"

  get '/treasuremaps' => 'treasuremaps#list', as: :treasuremaps
  get '/treasuremaps/new' => 'treasuremaps#new', as: :new_treasuremap
  get '/treasuremaps/:id' => 'treasuremaps#show', as: :treasuremap
  get '/treasuremaps/:id/edit' => 'treasuremaps#edit', as: :edit_treasuremap
  post 'treasuremaps' => 'treasuremaps#create', as: :create_treasuremap
  delete 'treasuremaps/:id' => 'treasuremaps#destroy', as: :delete_treasuremap
  patch 'treasuremaps/:id' => 'treasuremaps#update'

  get 'treasuremaps/:id/photos/new' => 'photos#new', as: :new_photo
  post 'treasuremaps/:id/photos/' => 'photos#create', as: :create_photo
  get 'treasuremaps/:id/photos/:photo_id' => 'photos#show', as: :photo

  get 'reset_location' => 'location#reset', as: :reset_map

  post 'current_location' => 'location#locate', as: :current_location

  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

  get 'api/photos' => 'api/photos#list'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :treasuremap
  attachment :attachment
end

app/models/treasuremap.rb
class Treasuremap < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user
  has_many :photos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true
  has_many :treasuremaps
  has_many :photos, through: :treasuremaps
end

app/controllers/api/me_controller.rb
class Api::MeController < ApplicationController
  before_action :doorkeeper_authorize!


  # GET /me.json
  def me
   @current_user = current_resource_owner
  end

  private

  # Find the user that owns the access token
  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController

  protect_from_forgery with: :null_session

  before_action :doorkeeper_authorize!


  before_action do
    request.format = :json
  end

  def list
    if doorkeeper_token
    @current_user = User.find(doorkeeper_token.resource_owner_id)
    @photos = @current_user.photos
    else
      render json: {error: "Could not find"}, status: 422
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

end

app/controllers/location_controller.rb
require 'cgi'
class LocationController < ApplicationController

  def locate
    @location = params[:location]

    results = JSON.parse(Http.get("http://locationiq.org/v1/search.php?key=adff1ce289577c56596f&format=json&q=#{CGI::escape(@location)}").body)

    if results != []
      session[:location] = results.first
      session[:location]["zoom"] = 14
      redirect_to root_path
    else
      redirect_to root_path, notice: "Address not found!"
    end
  end

  def reset
    session[:location] = nil
    redirect_to root_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    def new
        @photo = Photo.new
        @treasuremap = Treasuremap.find_by id: params[:id]
    end

    def create
        @photo = Photo.new
        @photo.location = params[:photo][:location]
        @photo.treasuremap_id = params[:id]
        @photo.attachment = params[:photo][:attachment]
        @photo.description = params[:photo][:description]
        @location = params[:photo][:location]

        results = JSON.parse(Http.get("http://locationiq.org/v1/search.php?key=adff1ce289577c56596f&format=json&q=#{CGI.escape(@location)}").body)
        @photo.latitude = results[0]['lat']
        @photo.longitude = results[0]['lon']

        if results != []
            if @photo.save

                session[:location]['zoom'] = 14
                redirect_to photo_path(photo_id: @photo.id, id: @photo.treasuremap.id), notice: "You're good to go!"
            else
                render :new, notice: 'Upload Failed!'
            end

        else
            render :new, notice: 'Location not found!'
        end
    end

    def show
        @treasuremap = Treasuremap.find_by id: params[:id]
        @photo = Photo.find_by id: params[:photo_id]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Welcome Back!'
    else
      flash.now[:alert] = "Username or Password does not match records"
      render :new
    end
  end


  def delete
    reset_session
    redirect_to root_path, notice: "Signed out!"
  end
end

app/controllers/treasuremaps_controller.rb
class TreasuremapsController < ApplicationController
  def list
    @treasuremaps = Treasuremap.all
  end

  def show
    @photo = Photo.new
    @treasuremap = Treasuremap.find_by id: params[:id]
    results = JSON.parse(Http.get("http://locationiq.org/v1/search.php?key=adff1ce289577c56596f&format=json&q=#{CGI::escape(@treasuremap.name)}").body)

    if results != []
      @treasuremap_location = results.first
      @treasuremap_location["zoom"] = 12
    else
      redirect_to edit_treasuremap_path(id: @treasuremap.id), notice: "Location not found, please update!"
    end
  end

  def new
   @treasuremap = Treasuremap.new
  end

  def create
    @treasuremap = Treasuremap.new
    @treasuremap.name = params[:treasuremap][:name]
    @treasuremap.user = @current_user

    if @treasuremap.save
      redirect_to treasuremap_path(id: @treasuremap.id), notice: "Map has been created! Add some Burritos!"
    else
      render :new
    end
  end

  def edit
    @treasuremap = Treasuremap.find_by id: params[:id]
  end

  def update
    @treasuremap = Treasuremap.find_by id: params[:id]
    @treasuremap.name = params[:treasuremap][:name]

    if @treasuremap.save
      redirect_to treasuremap_path(id: @treasuremap.id), notice: "Map Edit Complete"
    else
      render :edit
    end
  end

  def destroy
    @treasuremap = Treasuremap.find_by id: params[:id]
    @treasuremap.photos.destroy
    @treasuremap.destroy
    redirect_to treasuremaps_path, notice: "Map Deleted!"
  end


  def show_photo
    @treasuremap = Treasuremap.find_by id: params[:id]
  end

  def new_photo
    @treasuremap = Treasuremap.find_by id: params[:id]
    @photo = Photo.new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You're good to go!"
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    @search_done = false
    @current_location = session[:location]
    if @current_location.nil?
      @current_location = { "lat" => 37.620584, "lon" => -97.259945, "zoom" => 5 }
    else
      @search_done = true
      lat = @current_location["lat"]
      lon = @current_location["lon"]

      url = "https://api.foursquare.com/v2/venues/search?query=burrito&ll=#{lat},#{lon}&client_id=QJNE4GB5I20ZNYEJMY2W0F05BJ2SRFBLI3LV4SXWMG2IRSC4&client_secret=HGZW1QT05VRLK2BKBT1XDRNE5IUI3SRZFGSHPDCD0RGUADOB&v=20160715"

      json = JSON.parse(Http.get(url).body)

      @venues = json["response"]["venues"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burrito Plunderer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path do %>
        <%= image_tag("http://thelaughingplanetcafe.com/images/burrito-special-icon.png", class: "navbar-brand") %>
      <% end %>
    </div>

    <% if @treasuremap && @treasuremap.name %>
      <div class="navbar-text reset-btn">
        <%= link_to "Upload Burrito", new_photo_path, class: "btn btn-success navbar-btn" %>
      </div>
      <% else %>
        <span class="burrito-find navbar-text" >Locate nearby Burritos</span>
    <% end %>

    <!-- <div class="navbar-right sign-in">
      <% if @current_user %>
      <div class="navbar-text">
        Signed in as <%= @current_user.email %>
        (<%= link_to "Sign Out", sign_in_path, method: :delete %>)
      </div>
      <% else %>
          <%= link_to "Sign In", sign_in_path, class: "btn btn-primary navbar-btn" %>
      <% end %>
    </div> -->
    <div class="navbar-text navbar-right reset-btn">
      <%= link_to "Reset Map", reset_map_path, class: "btn btn-danger navbar-btn" %>
    </div>
    <div class="navbar-text navbar-right reset-btn">
      <% if @current_user %>
      <%= link_to "Your Treasure Maps", treasuremaps_path, class: "btn btn-danger navbar-btn" %>
      <% end %>
    </div>
  </div>
</nav>
<div class="container notices">
  <% if notice %>
    <div class="alert alert-info text-center" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger text-center" role="alert">
      <%= alert %>
    </div>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/photos/new.html.erb
<div class="container">
  <div class="well">
      <%= simple_form_for @photo, url:create_photo_path do |f| %>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.input :attachment, as: :file, class: "form-control" %>
            </div>
          </div>

          <div class="col-xs-6">
            <div class="form-group">
              <%= f.submit "Add Burrito", class: "btn btn-primary btn-block"%>
            </div>
          </div>

        </div>
      <% end %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="container">
  <br>
  <h1 class="text-center"> <%= @photo.description %> </h1>
  <h4 class="text-center">Get yours at: <%= @photo.location %> </h4>

<div class="text-center">
  <%= image_tag attachment_url(@photo, :attachment, :fill, 300, 300, format: "jpg") %>
</div>


</div>

app/views/treasuremaps/_form.html.erb
<div class="well">
<%= form_for @treasuremap do |f| %>

  <div class="form-group">
    <%= f.label :name, "Where are these Burritos? (City / Country)" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary"%>
  </div>
<% end %>

</div>

app/views/treasuremaps/edit.html.erb
<div class="container">
  <% if @treasuremap.errors.any? %>

    <div class="alert alert-danger" role="alert">
      <% @treasuremap.errors.full_messages.each do |error| %>
        <%= error %><br>
      <% end %>
    </div>

  <% end %>

<div class="new-form">
  <%= render partial: 'form' %>
</div>

<div class="">
   <%= link_to "Delete Map", treasuremap_path(id: @treasuremap.id), method: :delete, class: "btn btn-danger" %>
</div>

</div>

app/views/treasuremaps/list.html.erb
<div class="container">


  <h3>  <%= link_to "Create New Treasuremap", new_treasuremap_path, class: "btn btn-primary" %> </h3><br>
    <% @treasuremaps.each do |treasuremap| %>

      <div class="col-xs-12">
        <%= link_to treasuremap.name, treasuremap_path(id: treasuremap.id), class: "map-title" %>
        <%= link_to "Edit", edit_treasuremap_path(id: treasuremap.id), class: "btn btn-default" %>
      </div>

    <% end %>
</div>

app/views/treasuremaps/new.html.erb
<div class="container">

<div class="new-form">
  <% if @treasuremap.errors.any? %>

    <div class="alert alert-danger" role="alert">
      <% @treasuremap.errors.full_messages.each do |error| %>
        <%= error %><br>
      <% end %>
    </div>

  <% end %>
  <%= render partial: 'form' %>
</div>

</div>

app/views/treasuremaps/show.html.erb
  <div id="main_map"></div>

  <script type="text/javascript">
      var mymap = L.map('main_map').setView([
          <%= @treasuremap_location["lat"]%>, <%= @treasuremap_location["lon"]%>
      ], <%= @treasuremap_location["zoom"] %>);
      L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
          attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
          maxZoom: 18,
          id: 'bentopi.0m113af1',
          accessToken: 'pk.eyJ1IjoiYmVudG9waSIsImEiOiJjaXFueDZhamwwMWNmZnlubmN3Mjkwa2N3In0.KDH8Lcc77hResaVfMezoJA'
      }).addTo(mymap);

      <% @treasuremap.photos.each do |photo|%>
      L.marker([<%= photo.latitude %>, <%= photo.longitude %>]).addTo(mymap).bindPopup

      ("<a href='/treasuremaps/<%=photo.treasuremap.id%>/photos/<%=photo.id%>'><%=photo.description%></a>");
      <% end %>
  </script>



  <div class="new-photo">
  <%= link_to "Upload Burrito!", new_photo_path %>
  </div>

app/views/users/new.html.erb
<div class="container">

<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @user.errors.full_messages.each do |msg| %>
     <%= msg %> <br>
     <% end %>
  </div>
<% end %>


  <div class="well">
    <%= form_for @user, url: create_user_path do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "Retype Password" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class:"btn btn-lg btn-primary" %>
      </div>
      <% end %>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="burrito-search form-inline">
    <%= form_tag current_location_path do %>
    <div class="form-group burrito-search-bar">
        <%= text_field_tag(:location, "", class: "form-control", placeholder: "Ye Address goes 'ere") %>
    </div>
    <div class="form-group">
        <%= submit_tag("Ahoy!", class: "btn btn-default") %>
    </div>
    <% end %>
</div>

<div id="main_map"></div>

<script type="text/javascript">
    var mymap = L.map('main_map').setView([
        <%= @current_location["lat"] %>, <%= @current_location["lon"]%>
    ], <%= @current_location["zoom"] %>);
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'bentopi.0m113af1',
        accessToken: 'pk.eyJ1IjoiYmVudG9waSIsImEiOiJjaXFueDZhamwwMWNmZnlubmN3Mjkwa2N3In0.KDH8Lcc77hResaVfMezoJA'
    }).addTo(mymap);

    <% if @search_done %>
      L.marker([<%= @current_location["lat"] %>, <%= @current_location["lon"]%>]).addTo(mymap).bindPopup("You are here!");
      <% @venues.each do |venue|%>
      L.marker([<%= venue["location"]["lat"] %>, <%= venue["location"]["lng"] %>]).addTo(mymap).bindPopup("<a href=<%= venue["url"] %>><%= venue["name"] %></a> <br> <%= venue["location"]["address"] %> <br> <%= venue["location"]["city"] %>, <%= venue["location"]["postalCode"] %>");
      <% end %>
    <% end %>


</script>